const {app,BrowserWindow,ipcMain}=require("electron");
const path=require("path"),fs=require("fs"),QRCode=require("qrcode"),nodemailer=require("nodemailer");
const {default:makeWASocket,useMultiFileAuthState,DisconnectReason,downloadMediaMessage}=require("@whiskeysockets/baileys");
let win,sock,reconnecting=false;
const dataDir=path.join(app.getPath("userData"),"whatsmail"),authDir=path.join(dataDir,"whatsapp-auth"),configFile=path.join(dataDir,"config.json");
function readConfig(){try{return JSON.parse(fs.readFileSync(configFile,"utf8"))}catch{return {email:"",smtpHost:"",smtpPort:465,smtpSecure:true,smtpUser:"",smtpPass:""}}}
function saveConfig(c){fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(configFile,JSON.stringify(c,null,2))}
function send(ch,p){if(win&&!win.isDestroyed())win.webContents.send(ch,p)}
function esc(v=""){return String(v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function chatEmail(m,media){const files=(media||[]).map(x=>'<div style="margin-top:10px;padding:12px;border-radius:12px;background:#172033">📎 '+esc(x.filename)+"</div>").join("");return '<div dir="rtl" style="font-family:Arial;background:#0b1020;padding:24px;color:#eef2ff"><div style="max-width:680px;margin:auto;background:#111827;border:1px solid #26324a;border-radius:20px;padding:22px"><h2>WhatsMail</h2><div style="color:#94a3b8">WhatsApp Conversation</div><div style="background:#172033;border-radius:14px;padding:14px;margin:18px 0"><b>'+esc(m.name||m.from)+'</b><div style="color:#94a3b8;font-size:12px">'+esc(m.from)+'</div></div><div style="background:#0f766e;border-radius:14px;padding:14px;white-space:pre-wrap">'+esc(m.text||"[מדיה]")+"</div>"+files+"</div></div>"}
async function sendEmail(m,media){const c=readConfig();if(!c.smtpHost||!c.smtpUser||!c.smtpPass||!c.email){send("status",{type:"warning",text:"הגדרות המייל עדיין לא הוגדרו."});return}const transporter=nodemailer.createTransport({host:c.smtpHost,port:Number(c.smtpPort||465),secure:Boolean(c.smtpSecure),auth:{user:c.smtpUser,pass:c.smtpPass}});await transporter.sendMail({from:c.smtpUser,to:c.email,subject:"WhatsMail — "+(m.name||m.from),html:chatEmail(m,media),text:m.text||"[מדיה]",attachments:(media||[]).map(x=>({filename:x.filename,content:x.buffer}))})}
async function startWhatsApp(){if(sock||reconnecting)return;reconnecting=true;fs.mkdirSync(authDir,{recursive:true});const {state,saveCreds}=await useMultiFileAuthState(authDir);sock=makeWASocket({auth:state,browser:["WhatsMail","Windows","1.0.0"],printQRInTerminal:false,markOnlineOnConnect:false});sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",async({connection,lastDisconnect,qr})=>{if(qr){send("qr",await QRCode.toDataURL(qr,{margin:2,width:280}));send("status",{type:"info",text:"סרוק QR מתוך WhatsApp > מכשירים מקושרים."})}if(connection==="open"){reconnecting=false;send("qr",null);send("status",{type:"success",text:"WhatsApp מחובר בהצלחה."})}if(connection==="close"){const code=lastDisconnect?.error?.output?.statusCode;sock=undefined;reconnecting=false;send("status",{type:"error",text:"החיבור נותק ("+(code||"unknown")+")"});if(code!==DisconnectReason.loggedOut)setTimeout(startWhatsApp,3000)}});sock.ev.on("messages.upsert",async({messages})=>{for(const m of messages){if(!m.message||m.key.fromMe)continue;const from=m.key.remoteJid||"",name=m.pushName||from.split("@")[0];let text=m.message.conversation||m.message.extendedTextMessage?.text||m.message.imageMessage?.caption||m.message.videoMessage?.caption||m.message.documentMessage?.caption||"";const media=[];const node=m.message.imageMessage||m.message.videoMessage||m.message.audioMessage||m.message.documentMessage;if(node)try{const buffer=await downloadMediaMessage(m,"buffer",{});media.push({filename:node.fileName||("whatsmail-"+Date.now()),buffer})}catch(e){send("status",{type:"warning",text:"לא ניתן היה להוריד קובץ מצורף."})}const event={id:m.key.id,from,name,text,timestamp:Date.now(),media:media.map(x=>({filename:x.filename}))};send("message",event);try{await sendEmail(event,media);send("status",{type:"success",text:"הודעה נשלחה למייל."})}catch(e){send("status",{type:"error",text:"שליחת המייל נכשלה: "+e.message})}}})}
function createWindow(){win=new BrowserWindow({width:1180,height:760,minWidth:900,minHeight:620,backgroundColor:"#070b14",webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,"index.html"))}
app.whenReady().then(createWindow);
ipcMain.handle("config:get",()=>readConfig());ipcMain.handle("config:save",(_,c)=>{saveConfig(c);return true});ipcMain.handle("whatsapp:start",async()=>{await startWhatsApp();return true});ipcMain.handle("whatsapp:logout",async()=>{try{await sock?.logout()}catch{}sock=undefined;fs.rmSync(authDir,{recursive:true,force:true});send("status",{type:"info",text:"WhatsApp נותק."});return true});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});
